### ISSUE TITLE
安装+启动+同步+初始显示和功能（桌面图标、所有一级栏目）测试

### ISSUE THREAD

**Issue by saleo** [saleo/skcal#20]
荣耀8（Android7.0 API24，FRD-AL00），正常！

**Comment by saleo** [comment]
NEXUS-6P-API27（Android8.1.0，API27）
![image](https://user-images.githubusercontent.com/2926834/49323163-2adc3c80-f552-11e8-8825-9b4e088d12b0.png)

桌面图标显示不对

**Comment by saleo** [comment]
NEXUS-5X-API24（Android7.0，API24）,上述测试正常，同步稍慢。
![image](https://user-images.githubusercontent.com/2926834/49323156-1d26b700-f552-11e8-80ef-2ba539a76a71.png)

**Comment by saleo** [comment]
> NEXUS-6P-API27（Android8.1.0，API27）
> ![image](https://user-images.githubusercontent.com/2926834/49323163-2adc3c80-f552-11e8-8825-9b4e088d12b0.png)
> 
> 桌面图标显示不对

已解决，但没能看到同步效果。。也没有进程在AS可见到

**Comment by saleo** [comment]
2018年12月19日 刘主任oppoA3（colorOS5,基于android8.1）:
1. 浏览器下载时，被应用商店截获、提示下载qq浏览器
2. 安装后桌面图标错误

**Comment by saleo** [comment]
20181219, 爸爸手机

**Comment by saleo** [comment]
20181219，方老师samsung n9500
1. 安装后桌面图标错误
2. 启动后提示“多次出现错误”后自动退出

**Comment by saleo** [comment]
2018年12月20日
自己在testin真机samsung 9500上测试，安装后桌面图标错误+没有同步数据

**Comment by saleo** [comment]
2018年12月20日
自己在AS自带模拟器nexus 6p API v27上测试,桌面圆形图标正常
没有同步数据到本地

**Comment by saleo** [comment]
更新后再次测试，桌面图标正常； 数据仍然没有同步到，虽然提示 ”刷新完成“。。浏览器下载，没有被劫持下载qq浏览器等软件
```
使用机型
SM-G9500

品牌
三星

型号
Galaxy S8

分辨率
1080*2220

系统
android 8.0.0

屏幕尺寸
5.8

CPU
骁龙835（MSM8998）

内存
4096

核心数
8

开始时间
2018-12-21 10:45

结束时间
2018-12-21 10:55

使用时长
10分钟
```

> 2018年12月20日
> 自己在testin真机samsung G9500上测试，安装后桌面图标错误+没有同步数据

![image](https://user-images.githubusercontent.com/2926834/50322268-5037e700-050f-11e9-9220-5a0acf421cae.png)

**Comment by saleo** [comment]
> 2018年12月20日
> 自己在AS自带模拟器nexus 6p API v27上测试,桌面圆形图标正常
> 没有同步数据到本地

如果没在安装后系统请求授权时，及时点击“确认日历授权” ，会出现错误：
E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                  Process: net.euse.calendar.debug, PID: 4886
                  java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{b9e63af 4886:net.euse.calendar.debug/u0a88} (pid=4886, uid=10088) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
                      at android.os.Parcel.readException(Parcel.java:2004)
                      at android.os.Parcel.readException(Parcel.java:1950)
                      at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
                      at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1924)
                      at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1913)
                      at net.euse.calendar.extensions.ContextKt$syncCalDAVCalendars$1.run(Context.kt:394)
                      at java.lang.Thread.run(Thread.java:764)

**Comment by saleo** [comment]
#28 遇到同步问题，继续在GM samsung Galaxy s7(api25 android7.1)上测试：成功同步到数据，不过多次显示 refresh complete..再立即用会#28中的nexus 6p,还是不能同步数据
